### **`Probability`**

# # 1. Your data table rows represent 1000 different clients picked at random and are independent.
# # 2. Each data sample (i.e. table row) has some attributes with random values (continuous and discrete) namely:
M = Marital status

ND = No. of dependents

AI = Client’s annual income

R = Risk associated to No-cashback

HA = Has previous approved loan

AA = Amount of previously approved loan

TA = Time until loan is approved

YA = Year of last approved loan

# import libararies

In [ ]:
#import libararies
import numpy as np
from scipy.stats import *

# 3. The marital status (M) 

In [ ]:
M = binom.rvs(n=1, p=0.6, size=1000)

# 4. The No. of dependents (ND)

In [ ]:
ND = poisson.rvs(mu=2,size=1000)

# 5. The client’s annual income in order of 1k (AI)

In [ ]:
AI = norm.rvs(loc=80, scale=20, size=1000)

# 6. The risk associated to No-cashback (R)

In [ ]:
R = 12*(ND+1)/AI

# 7. Has a previous approved loan (HA)

In [ ]:
HA = binom.rvs(n=1, p=0.3, size=1000)

# 8. The amount of previously approved loan (AA)

In [ ]:
N = norm.rvs(loc=100, scale=10, size=1000)
AA = HA*(0.1*AI+R*N)

# 9. The time until loan is approved(TA)

In [ ]:
expon = expon.rvs(scale=2, size=1000)
TA = HA*expon

# 10. The year of last approved loan (YA)

In [ ]:
U = uniform.rvs(loc=2010,scale=10,size=1000)
YA = HA*U

# a. Probability to get a loan application by a single client with 2 parent dependents

In [ ]:
client2parent = 0;
#for loop to count no. of clients is single and have 2 parent dependents
for i in range(1000):
    if M[i] == 0 and ND[i] == 2:
        client2parent += 1 
print(client2parent/1000)

0.108


# b. Probability that a loan application will take more than 5 months to get approved

In [ ]:
#get list of loan that will take 5 months to get approved 
TA5months = TA[TA > 5]
#Probability that a loan application will take more than 5 months to get approved and has previous approved loan.
print(len(TA5months)/len(HA[HA == 1]))

0.07894736842105263


# c. Probability that a loan less than 100k will be approved to a client given that he has been cashed a previous loan?

In [ ]:
#HAAndAA probability of  a loan less than 100k will be approved and he has been cashed a previous loan.
probOfHAAndAA = np.count_nonzero(AA < 100) & np.count_nonzero(HA)
#calculate conditional probability
print( probOfHAAndAA / np.count_nonzero(HA))

0.8947368421052632


# d. Describe the relationship between the no. of dependents (ND) and the risk factor (R)

In [ ]:
covOfNDAndR = np.cov(ND,R)
corrOfNDAndR = np.corrcoef(ND,R)
print(covOfNDAndR)
print(corrOfNDAndR)
#Comment 
#Relation between ND and R is proportional linear because the sign of Correlation between var's (+) and strength of relation is 0.62563.
#correlation of ND and R = correlation of R and ND.

[[1.8793033  0.31174422]
 [0.31174422 0.08507478]]
[[1.         0.77964978]
 [0.77964978 1.        ]]


# e. Describe the relationship between the annual income (AI) and the risk factor (R)

In [ ]:
covOfAIAndR = np.cov(AI,R)
corrOfAIAndR = np.corrcoef(AI,R)
print(covOfAIAndR)
print(corrOfAIAndR)
#Comment 
#Relation between AI and R is inversely linear because the sign of Correlation between to var's is (-) and strength of relation is 0.45174745.
#correlation of AI and R = correlation of R and AI.

[[ 4.02959987e+02 -3.12562676e+00]
 [-3.12562676e+00  8.50747788e-02]]
[[ 1.        -0.5338334]
 [-0.5338334  1.       ]]
